name: Create release
on:
  workflow_dispatch:
    inputs:
      version:
        description: '⚠ be sure of yourself ⚠'
        required: false
        default: ''

jobs:
  release:
    environment: 'Release'
    runs-on: ubuntu-latest
    env:
      GITHUB_CREDENTIALS: ${{ secrets.CLI_RELEASE }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run build
      - name: Setup credentials
        run: |
          git config --global user.email action@github.com
          git config --global user.name GitHub Action
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Publish
        run: npm run release
